### ISSUE TITLE
Download HomeBrew JSON - All HomeBrew Packages

### ISSUE THREAD

**Issue by larson-carter** [MLH-Fellowship/0.0.1-API-Parser#5]
We need to be able to make a GET request against the HomeBrew current packages API then with that request we need to store all of the JSON prettified into a .json file

The file storage format will be HOMEBREW-$DATE-$TIME.json that way we can always check what the latest version is.

Source:
https://formulae.brew.sh/docs/api/

**Comment by BaffourAdu** [comment]
I would be handling this if no one has assigned himself to this issue

**Comment by BaffourAdu** [comment]
@larson-carter out of the 3 APIs below, which one do we need?
- https://formulae.brew.sh/api/formula.json
- https://formulae.brew.sh/api/formula-linux.json
- https://formulae.brew.sh/api/cask.json

**Comment by BaffourAdu** [comment]
@larson-carter I would create my branch of your current branch `feat/ruby-project` to prevent merge conflicts

**Comment by larson-carter** [comment]
Alright, have you created it yet?

**Comment by larson-carter** [comment]
This has been merged into master.
